### PR TITLE
Fix IngressRoute weights implementation

### LINKED ISSUE #477: IngressRoute weights shouldn't need to add up to 100
Currently if the sum of the `weight` values for a set of Services in a Route is not equal to 100, then Envoy will fail to accept the updated configuration from Contour.

```
[2018-06-28 03:32:29.523][1][warning][upstream] source/common/config/grpc_mux_impl.cc:188] gRPC config for type.googleapis.com/envoy.api.v2.RouteConfiguration update rejected: Sum of weights in the weighted_cluster should add up to 100
[2018-06-28 03:32:29.523][1][warning][config] bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_mux_subscription_lib/common/config/grpc_mux_subscription_impl.h:69] gRPC config for type.googleapis.com/envoy.api.v2.RouteConfiguration rejected: Sum of weights in the weighted_cluster should add up to 100
```

The IngressRoute design is not defined, but I believe previous discussions concluded that Contour would translate the weights provided by the user into acceptable ratios for envoy.

### PR DESCRIPTION
**Pull request by stevesloka**
This fixes #477 and uses the following strategy:

- If no weights are specified, it's assumed even distribution
- If all weights are specified then they are used and the "total" weight is the sum of those specified. (ex. If weights are 20, 30, 20 for three upstreams, the total weight would be 70)
- If some weights are specified but others are not, then it's assumed that upstream not specified gets zero traffic and its weight is set to zero

Signed-off-by: Steve Sloka <steves@heptio.com>

### CODE REVIEW

**Comment by alexbrand** [comment]
We discussed (on Slack, a bit) the last bullet:
> If some weights are specified but others are not, then it's assumed that upstream not specified gets zero traffic and its weight is set to zero

@stevesloka brought up a great point that, if we don't default weights to zero and consider the ingressroute invalid, it will most likely be difficult to troubleshoot what is going on with an ingressroute when the user misses a weight in one of the upstreams: "Is the ELB not working?", "Is contour the issue?", etc.

The downside is that we are introducing convention or "magic" that I am not sure we have precedent for. I am torn here.

**Comment by davecheney** [comment]
I'm sorry this PR won't apply any more after the refactoring for #454. Hopefully by 2/July it should be clear where to rebase this too (I'm in the process of merging the various internal/{route,cluster,listener} packages back into internal/contour)

**Comment by stevesloka** [comment]
@davecheney @alexbrand this is ready for review, please take a look. 

The other open question is in regards to handling values not specified. Right now (in this PR) if you do not specify a weight on a service, but you do for others, the unspecified service will not receive traffic. If no weights are defined, then all services get even distribution.

**Comment by davecheney** [comment]
> The other open question is in regards to handling values not specified. Right now (in this PR) if you do not specify a weight on a service, but you do for others, the unspecified service will not receive traffic. If no weights are defined, then all services get even distribution.

seems reasonable.

File: internal/dag/dag.go [hunk 1]
```diff
@@ -491,10 +492,11 @@ type Route struct {
 
 func (r *Route) Prefix() string { return r.path }
 
-func (r *Route) addService(s *Service) {
+func (r *Route) addService(s *Service, weight *int) {
 	if r.services == nil {
 		r.services = make(map[portmeta]*Service)
 	}
+	s.Weight = weight
```
Comment (davecheney) [inline internal/dag/dag.go]: I don't think this field belongs on the service object. Unlike https://github.com/heptio/contour/pull/498#discussion_r199679683 I think that a service referenced with two different weights is a different service. This mirrors the way envoy models service weighting; the weighted configuration goes into the RDS configuration--you'll never find anything to do with a cluster's weight on the cluster object in CDS.

I think we can live with this for beta.1, but please raise an issue to address it for 0.6 final.

File: internal/dag/dag.go [hunk 2]
```diff
@@ -557,12 +559,13 @@ type Vertex interface {
...
 }
 
-// Secret represents a K8s Sevice as a DAG vertex. A Serivce is
+// Service represents a K8s Sevice as a DAG vertex. A Service is
 // a leaf in the DAG.
 type Service struct {
 	object *v1.Service
 
 	*v1.ServicePort
+	Weight *int
```
Comment (davecheney) [inline internal/dag/dag.go]: I suggest making this an int, not a *int, then we don't need to deal with nil fields and we can define what a weight of zero means; we can say it means unset. If someone references a service with a weight of zero in the ingressroute document, we can filter it out during dag build time. (but see my comments above about this field)

File: internal/contour/route.go [hunk 3]
```diff
@@ -234,12 +230,45 @@ func prefixmatch(prefix string) route.RouteMatch {
...
+	for _, i := range be {
+
+		// Create the empty upstream
+		upstream := route.WeightedCluster_ClusterWeight{
+			Name:   hashname(60, i.Namespace(), i.Name(), strconv.Itoa(int(i.Port))),
+			Weight: &types.UInt32Value{Value: uint32(0)},
+		}
+
+		// If weight is passed, then use otherwise calculate
+		if i.Weight != nil {
```
Comment (davecheney) [inline internal/contour/route.go]: We could modify dag.recompute so that weight was always non nil (see my comment below) and the weight value was always valid, ie more than zero. 

Then totalweight would never be zero and we wouldn't have to do a fixup.

File: internal/dag/dag.go (hunk 1 above)
Comment (stevesloka) [reply internal/dag/dag.go]: Yup that's a good point, let me look to refactor it a bit.

Comment (stevesloka) [reply internal/dag/dag.go]: > I think that a service referenced with two different weights is a different service
Previous conversations around this lead to this being an error. Are we going to support different weights / lb algo / healthchecks or are those all errors?

**Comment by stevesloka** [comment]
I change the `Weight` type to be a non-pointer.

File: internal/contour/route.go [hunk 4]
```diff
@@ -234,12 +230,40 @@ func prefixmatch(prefix string) route.RouteMatch {
...
-func actionroute(namespace, name string, port int, ws bool, timeout time.Duration) *route.Route_Route {
-	cluster := hashname(60, namespace, name, strconv.Itoa(port))
+func actionroute(be []*dag.Service, ws bool, timeout time.Duration) *route.Route_Route {
+	totalWeight := 0
+	upstreams := []*route.WeightedCluster_ClusterWeight{}
+
+	// Loop over all the upstreams and add to slice
+	for _, i := range be {
+
+		// Create the empty upstream
```
Comment (alexbrand) [inline internal/contour/route.go]: nit: does this comment still apply?

File: internal/contour/route.go [hunk 5]
```diff
@@ -234,12 +230,40 @@ func prefixmatch(prefix string) route.RouteMatch {
 
 // action computes the cluster route action, a *route.Route_route for the
 // supplied ingress and backend.
-func actionroute(namespace, name string, port int, ws bool, timeout time.Duration) *route.Route_Route {
-	cluster := hashname(60, namespace, name, strconv.Itoa(port))
+func actionroute(be []*dag.Service, ws bool, timeout time.Duration) *route.Route_Route {
```
Comment (alexbrand) [inline internal/contour/route.go]: nit: can `be` be `services` instead?

File: internal/contour/route.go [hunk 6]
```diff
@@ -234,12 +230,40 @@ func prefixmatch(prefix string) route.RouteMatch {
...
+	totalWeight := 0
+	upstreams := []*route.WeightedCluster_ClusterWeight{}
+
+	// Loop over all the upstreams and add to slice
+	for _, i := range be {
```
Comment (alexbrand) [inline internal/contour/route.go]: nit: can `i` be `svc` instead?

**Comment by stevesloka** [comment]
@alexbrand I updated per your comments

File: internal/contour/route.go [hunk 7]
```diff
@@ -234,12 +230,39 @@ func prefixmatch(prefix string) route.RouteMatch {
 
 // action computes the cluster route action, a *route.Route_route for the
 // supplied ingress and backend.
-func actionroute(namespace, name string, port int, ws bool, timeout time.Duration) *route.Route_Route {
-	cluster := hashname(60, namespace, name, strconv.Itoa(port))
+func actionroute(services []*dag.Service, ws bool, timeout time.Duration) *route.Route_Route {
```
Comment (davecheney) [inline internal/contour/route.go]: Please add a test for actionroute, it's not just a helper for constructing some annoying grpc data object any more, the totalWeight business logic needs a test.

**Comment by davecheney** [comment]
I'm fixing the merge conflicts and will get this over the line tonight
