### PR TITLE
cmd/contour: moving flag.Parse out of init()

### LINKED ISSUE #371: contour --help hijacked by glog
Here's the problem
```
% contour --help
Usage of contour:
  -alsologtostderr
        log to standard error as well as files
  -log_backtrace_at value
        when logging hits line file:N, emit a stack trace
  -log_dir string
        If non-empty, write log files in this directory
  -logtostderr
        log to standard error instead of files
  -stderrthreshold value
        logs at or above this threshold go to stderr
  -v value
        log level for V logs
  -vmodule value
        comma-separated list of pattern=N settings for file-filtered logging
```
^ these aren't contour's flags. They come from glog, and they come from glog because we call `flag.Parse` before main.main. 

We can't avoid that call because glog uses flag.Parse as a side channel to initalise itself, see #118, so what we can do is move the call to flag.Parse _just_ before the we create a k8s client, but after kingpin has had a chance to parse flags properly.

### PR DESCRIPTION
**Pull request by dvdmuckle**
Fixes #371 

This must be done as glog requires flag.Parse before being used by anything else for logging purposes. However, doing this before any flags are defined with kingpin will override our flags, thus flag.Parse must be called after our kingpin calls, but before creating a new client.

Signed-off-by: David Muckle <dvdmuckle@dvdmuckle.xyz>

### CODE REVIEW

**Comment by dvdmuckle** [comment]
Sorry about that, had to recreate the PR to sign off.

**Comment by davecheney** [comment]
Thanks for your PR. Here are some tips for writing a goo PR and a good commit.

The title of the commit, and the PR should describe what will happen to the codebase if this change is applied. "Fixes #371" is ok, but "move flag.Parse out of init" would be better.

The body of the PR should include the words "Fixes #371" at the start, on their own. These words are special and github will close the associated issue when the PR is merged.

The rest of the body should describe _how_ and or _why_ this PR should be merged. The why is simple, it's described in #371. The how could be optional in some cases, but in this case it should probably be something like 

> glog requires flag.Parse to be called before anything that uses glog attempts to log. In this case the glog callers are the kubernetes client, so we move he call to flag.Parse just before calling k8s.NewClient.


Lastly, you dno't need to recreate the PR to sign it; `git commit -s --amend` will do.

File: cmd/contour/contour.go [hunk 1]
```diff
@@ -123,6 +116,11 @@ func main() {
 		// buffer notifications to t to ensure they are handled sequentially.
 		buf := k8s.NewBuffer(&g, t, log, 128)
 
+		// this is necessary due to #113 wherein glog neccessitates a call to flag.Parse
```
Comment (davecheney) [inline cmd/contour/contour.go]: As much as I am a fan of this salty comment (when #118 was fixed I explicitly asked for this comment because I was so pissed off) we should probably change the comment to something more helpful for future archeologists.

(also the issue number in the comment is wrong, it should be 118, not 113 -- oops)

```
// client-go uses glog which requires initialisation as a side effect of calling
// flag.Parse (see #118 and https://github.com/golang/glog/blob/master/glog.go#L679)
// However, kingpin owns our flag parsing, so we defer calling flag.Parse until 
// this point to avoid the Go flag package from rejecting flags which are defined
// in kingpin. See #371

**Comment by davecheney** [comment]
@dvdmuckle gentle nudge

**Comment by dvdmuckle** [comment]
Sorry, amended my last commit with a correction to the comment and the commit message.

**Comment by davecheney** [comment]
> Sorry, amended my last commit with a correction to the comment and the commit message.

and the PR title and description :)

**Comment by dvdmuckle** [comment]
Ah, right, updated those too.

**Comment by davecheney** [comment]
Pretty close. Thanks, i'll take it from here.
