### PR TITLE
internal/contour: upstream-protocol annotation support

### LINKED ISSUE #152: Unable to connect to a http/2 gRPC application through envoy/contour
First of all, thanks for this project. Looks very promising.

TLTR, I'm receiving `upstream connect error or disconnect/reset before headers` which seems that I misconfigured something but I'm not able to discover what!

Lets get hands dirty, I deployed everything in GKE with Kubernetes 1.8.6. Two namespaces `edge-system` & `space-system`. `edge-system` contains contour + envoy. `space-system` contains my testing gRPC service (take a look to the [proto](#test.proto)). The application service is working as expected because I made aN in-cluster test by running an one-shot client container and check if everything is behaving as I would expect.

It worked even deploying it inside the envoy container. Concretely, I made two tests, one accessing directly to the endpoint and the other going through the service: 

```
$> kubectl get services/test -n space-system
NAME      TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
test      ClusterIP   10.39.243.31   <none>        8080/TCP   19h
$> kubectl get endpoints/test -n space-system
NAME      ENDPOINTS         AGE
test      10.36.12.5:8080   19h
$> kubectl exec -ti contour-84fc9b758d-4gnx4 -c envoy -n edge-system sh
/ # ./test-client -addr 10.39.243.31:8080
2018/01/15 09:36:06 GetUser(_) = id:"ec5ae4c1-35ee-42d1-95cc-1ce3bc7bb551" display_name:"Gorka" 
2018/01/15 09:36:07 id:"b1d577a0-f9e9-454b-af8a-024e4c52c20c" content:"Door left opened" 
2018/01/15 09:36:08 id:"d263e680-d1a9-41b6-93a1-e61eabd6de57" content:"Intrusion detected" 
^C
/ # ./test-client -addr 10.36.12.5:8080
2018/01/15 09:36:06 GetUser(_) = id:"ec5ae4c1-35ee-42d1-95cc-1ce3bc7bb551" display_name:"Gorka" 
2018/01/15 09:36:19 id:"b1d577a0-f9e9-454b-af8a-024e4c52c20c" content:"Door left opened" 
2018/01/15 09:36:20 id:"d263e680-d1a9-41b6-93a1-e61eabd6de57" content:"Intrusion detected" 
```

So the conclusion is that something is going between envoy and the upstream. Now lets dig into the ingresses and if contour configure envoy as expected. I created just one ingress `test.mydomain.com`:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
  namespace: space-system
  annotations:
    kubernetes.io/ingress.class: "contour"
spec:
  rules:
  - host: test.mydomain.com
    http:
      paths:
      - backend:
          serviceName: test
          servicePort: 8080
        path: /
```

And seems like `contour` caught it:

```
$> kubectl exec -ti contour-84fc9b758d-4gnx4 -c envoy -n edge-system sh
/ # wget -O - http://127.0.0.1:9001/routes | cat
Connecting to 127.0.0.1:9001 (127.0.0.1:9001)
-                   [
{
"version_info": "40",
"route_config_name": "ingress_http",
"cluster_name": "xds_cluster",
"route_table_dump": {"name":"ingress_http","virtual_hosts":[{"name":"test.mydomain.com","domains":["test.mydomain.com"],"routes":[{"match":{"prefix":"/"},"route":{"cluster":"space-system/test/8080"}}]}]}
}
]
/ # wget -O - http://127.0.0.1:9001/listeners | cat
Connecting to 127.0.0.1:9001 (127.0.0.1:9001)
-                   ["0.0.0.0:8080"]
/ # wget -O - http://127.0.0.1:9001/clusters | grep space-system
Connecting to 127.0.0.1:9001 (127.0.0.1:9001)
-                   space-system/test/http::default_priority::max_connections::1024
space-system/test/http::default_priority::max_pending_requests::1024
space-system/test/http::default_priority::max_requests::1024
space-system/test/http::default_priority::max_retries::3
space-system/test/http::high_priority::max_connections::1024
space-system/test/http::high_priority::max_pending_requests::1024
space-system/test/http::high_priority::max_requests::1024
space-system/test/http::high_priority::max_retries::3
space-system/test/http::added_via_api::true
space-system/test/http::10.36.12.5:8080::cx_active::0
space-system/test/http::10.36.12.5:8080::cx_connect_fail::0
space-system/test/http::10.36.12.5:8080::cx_total::0
space-system/test/http::10.36.12.5:8080::rq_active::0
space-system/test/http::10.36.12.5:8080::rq_error::0
space-system/test/http::10.36.12.5:8080::rq_success::0
space-system/test/http::10.36.12.5:8080::rq_timeout::0
space-system/test/http::10.36.12.5:8080::rq_total::0
space-system/test/http::10.36.12.5:8080::health_flags::healthy
space-system/test/http::10.36.12.5:8080::weight::1
space-system/test/http::10.36.12.5:8080::region::ap-southeast-2
space-system/test/http::10.36.12.5:8080::zone::2b
space-system/test/http::10.36.12.5:8080::sub_zone::banana
space-system/test/http::10.36.12.5:8080::canary::false
space-system/test/http::10.36.12.5:8080::success_rate::-1
space-system/test/8080::default_priority::max_connections::1024
space-system/test/8080::default_priority::max_pending_requests::1024
space-system/test/8080::default_priority::max_requests::1024
space-system/test/8080::default_priority::max_retries::3
space-system/test/8080::high_priority::max_connections::1024
space-system/test/8080::high_priority::max_pending_requests::1024
space-system/test/8080::high_priority::max_requests::1024
space-system/test/8080::high_priority::max_retries::3
space-system/test/8080::added_via_api::true
space-system/test/8080::10.36.12.5:8080::cx_active::0
space-system/test/8080::10.36.12.5:8080::cx_connect_fail::0
space-system/test/8080::10.36.12.5:8080::cx_total::13
space-system/test/8080::10.36.12.5:8080::rq_active::0
space-system/test/8080::10.36.12.5:8080::rq_error::13
space-system/test/8080::10.36.12.5:8080::rq_success::0
space-system/test/8080::10.36.12.5:8080::rq_timeout::0
space-system/test/8080::10.36.12.5:8080::rq_total::13
space-system/test/8080::10.36.12.5:8080::health_flags::healthy
space-system/test/8080::10.36.12.5:8080::weight::1
space-system/test/8080::10.36.12.5:8080::region::ap-southeast-2
space-system/test/8080::10.36.12.5:8080::zone::2b
space-system/test/8080::10.36.12.5:8080::sub_zone::banana
space-system/test/8080::10.36.12.5:8080::canary::false
space-system/test/8080::10.36.12.5:8080::success_rate::-1
```

It seems like something is not working properly in envoy (see `rq_error`s) but I cannot figure out what. Checking Envoys log didn't help at all (at least for me) because it seems like access and error logs are interleaved and I didn't find any way to debug application errors easily...

Sorry for the long-post, can anyone help ME shedding some light diagnosing what could be causing this?

Thanks!

<a name="test.proto"></a>`test.proto`:
```
syntax = "proto3";

package test;

service TestService {
  // Client sends a single request and gets back a single response.
  rpc GetUser(GetUserRequest) returns (GetUserResponse);

  // Streams from the server.
  rpc GetEvents(GetEventsRequest) returns (stream Event);
}

message GetUserRequest {
  string id = 1;
}

message GetUserResponse {
  string id = 1;
  string display_name = 2;
}

message GetEventsRequest {
}

message Event {
  string id = 1;
  string content = 2;
}
```

### PR DESCRIPTION
**Pull request by glerchundi**
Fixes #152

Signed-off-by: Gorka Lerchundi Osa <glertxundi@gmail.com>

### CODE REVIEW

**Comment by glerchundi** [comment]
Early PR, just to know if it's what we want. Once accepted I'll add comments and tests.

File: internal/contour/annotations.go [hunk 1]
```diff
@@ -76,6 +78,33 @@ func parseAnnotationUInt32(annotations map[string]string, annotation string) *ty
 	return &types.UInt32Value{Value: uint32(v)}
 }
 
+// parseUpstreamProtocols parses the annotations map for a contour.heptio.com/upstream-protocol.{protocol}
+// where 'protocol' identifies which protocol must be used in the upstream.
+// If the value is not present, or malformed, then an empty map is returned.
+func parseUpstreamProtocols(annotations map[string]string, annotation string, protocols []string) map[string]struct{} {
+	up := make(map[string]struct{})
```
Comment (davecheney) [inline internal/contour/annotations.go]: please use a map[string]bool

File: internal/contour/annotations.go [hunk 2]
```diff
@@ -76,6 +78,33 @@ func parseAnnotationUInt32(annotations map[string]string, annotation string) *ty
...
+	for _, protocol := range protocols {
+		ports, ok := annotations[fmt.Sprintf("%s.%s", annotation, protocol)]
+		if !ok {
+			continue
+		}
+
+		for _, port := range strings.Split(ports, ",") {
+			if port != "" {
```
Comment (davecheney) [inline internal/contour/annotations.go]: you'll have to use a strings.Trim here because someone might write `"80, 443"`

File: internal/contour/annotations.go [hunk 3]
```diff
@@ -76,6 +78,33 @@ func parseAnnotationUInt32(annotations map[string]string, annotation string) *ty
 	return &types.UInt32Value{Value: uint32(v)}
 }
 
+// parseUpstreamProtocols parses the annotations map for a contour.heptio.com/upstream-protocol.{protocol}
+// where 'protocol' identifies which protocol must be used in the upstream.
+// If the value is not present, or malformed, then an empty map is returned.
+func parseUpstreamProtocols(annotations map[string]string, annotation string, protocols []string) map[string]struct{} {
```
Comment (davecheney) [inline internal/contour/annotations.go]: make this `protocols ...string`

File: internal/contour/cluster_test.go [hunk 4]
```diff
@@ -33,7 +35,7 @@ func TestClusterCacheRecomputeService(t *testing.T) {
 	}{
 		"add unnamed service": {
 			oldObj: nil,
-			newObj: service("default", "kuard",
+			newObj: service("default", "kuard", nil,
```
Comment (davecheney) [inline internal/contour/cluster_test.go]: please add a new helper, something like serviceWithProtocol that takes the parameter which has been nil`d out here.

File: internal/contour/annotations.go (hunk 1 above)
Comment (glerchundi) [reply internal/contour/annotations.go]: Ok

File: internal/contour/annotations.go (hunk 2 above)
Comment (glerchundi) [reply internal/contour/annotations.go]: OMG, beginner failure. Will do.

File: internal/contour/annotations.go (hunk 3 above)
Comment (glerchundi) [reply internal/contour/annotations.go]: Ok

File: internal/contour/cluster_test.go (hunk 4 above)
Comment (glerchundi) [reply internal/contour/cluster_test.go]: I removed the parameter from `service` and included an additional `serviceWithAnnotations` in order to avoid the creation of nil-able protocol struct.  let me know if even so you want me to change with your proposed semantics.

**Comment by glerchundi** [comment]
@davecheney i think it's ready for the second pass.

**Comment by davecheney** [comment]
Thanks. This looks good but if it's ok with you I'm going to hold off landing this til monday, once the 0.4 release is out (next 24 hours).

**Comment by glerchundi** [comment]
I'm ok with that @davecheney, i'll remove the release notes entry then. Thanks!

**Comment by glerchundi** [comment]
@davecheney it's ready for merge once `0.4` was released.

**Comment by glerchundi** [comment]
Just to point something related here. As NGINX has announced support for gRPC, the community behind ingress-nginx has filed an issue to support it. Nothing on the table yet but ingress-nginx maintainer proposal was to include a new **Ingress** annotation `nginx.ingress.kubernetes.io/use-grpc`.

**Comment by glerchundi** [comment]
@davecheney friendly ping.

File: internal/contour/cluster.go [hunk 5]
```diff
@@ -27,6 +28,11 @@ const (
 	annotationMaxPendingRequests = "contour.heptio.com/max-pending-requests"
 	annotationMaxRequests        = "contour.heptio.com/max-requests"
 	annotationMaxRetries         = "contour.heptio.com/max-retries"
+	annotationUpstreamProtocol   = "contour.heptio.com/upstream-protocol"
+)
+
+const (
+	upstreamProtocolH2 = "h2"
```
Comment (davecheney) [inline internal/contour/cluster.go]: I don't think this needs a constant longer than it's value, we only use it in one place and it's not going to change so maybe just use the "h2" literal where needed

File: internal/contour/cluster.go [hunk 6]
```diff
@@ -123,7 +132,7 @@ func (cc *ClusterCache) recomputeService(oldsvc, newsvc *v1.Service) {
 	}
 }
 
-func edscluster(svc *v1.Service, portString string, config *v2.Cluster_EdsClusterConfig) *v2.Cluster {
+func edscluster(svc *v1.Service, portString string, upstreamProtocols map[string]bool, config *v2.Cluster_EdsClusterConfig) *v2.Cluster {
```
Comment (davecheney) [inline internal/contour/cluster.go]: I don't think this is right. I think what is needed is a a map of portStrings to protocol. I don't think you need to pass a map into edscluster, just pass in something representing the upstream l7 protocol; ie

edscluster(svc, "admin", "h2", config{...})

It doesn't need to be a string, (maybe an enumeration like)
const (
    protocolUnknown = 0
    protocolHTTP1 = 1
    protocolHTTP2 = 2
    protocolHTTPS = 3
)

but I don't think you need to pass in a map of values if edscluster doesn't need to consult each of those values.

**Comment by glerchundi** [comment]
> Thanks for working on this, I think it's pretty close.
> 
> Sorry for the delay, I'm currently in Seattle for an engineering offsite.

Don't worry!

File: internal/contour/cluster.go (hunk 5 above)
Comment (glerchundi) [reply internal/contour/cluster.go]: i kept the constant because now i'm using it more than once. Tell me if you want me to remove the constant and hardcode them instead.

**Comment by davecheney** [comment]
> Nothing on the table yet but ingress-nginx maintainer proposal was to
include a new *Ingress*annotation nginx.ingress.kubernetes.io/use-grpc.

They're wrong. The l7 protocol of the service is a property of the service
object, not the ingress.

File: internal/contour/cluster.go (hunk 6 above)
Comment (glerchundi) [reply internal/contour/cluster.go]: > I don't think this is right. I think what is needed is a a map of portStrings to protocol. I don't think you need to pass a map into edscluster, just pass in something representing the upstream l7 protocol; ie

I agree, but I went with string I'll let you decide in further PRs how do you prefer to proceed.

> It doesn't need to be a string, (maybe an enumeration like)
> const (
> protocolUnknown = 0
> protocolHTTP1 = 1
> protocolHTTP2 = 2
> protocolHTTPS = 3
> )
> 
> but I don't think you need to pass in a map of values if edscluster doesn't need to consult each of those values.

This means that Envoy doesn't support h2c?

**Comment by glerchundi** [comment]
> They're wrong. The l7 protocol of the service is a property of the service
> object, not the ingress.

I'm with you.

**Comment by glerchundi** [comment]
This should be ready for the third and hopefully final pass! ;)

File: internal/contour/cluster.go [hunk 7]
```diff
@@ -143,6 +153,10 @@ func edscluster(svc *v1.Service, portString string, config *v2.Cluster_EdsCluste
 		cluster.CircuitBreakers = &v2cluster.CircuitBreakers{Thresholds: []*v2cluster.CircuitBreakers_Thresholds{thresholds}}
 	}
 
+	if upstreamProtocol == upstreamProtocolHTTP2 {
```
Comment (davecheney) [inline internal/contour/cluster.go]: given we're probably going to add TLS or something for http1/1+tls, what about a switch here
```
switch upstreamProtocol {
case upstreamProtocolHTTP2:
    cluster.Http2ProtocolOptions = &core.Http2ProtocolOptions{}
}
```

File: internal/contour/cluster.go (hunk 5 above)
Comment (davecheney) [reply internal/contour/cluster.go]: please use "h2" upstreamProtocolh2 is longer without conveying more information. Or to say it another way, a constant should not encode it's value in its name.

File: internal/contour/cluster.go (hunk 7 above)
Comment (glerchundi) [reply internal/contour/cluster.go]: This is the first thing I thought but then I supposed you'll prefer that if there weren't more than one case a single if is more appropriate! haha

Will change now.

Comment (glerchundi) [reply internal/contour/cluster.go]: Done.

File: internal/contour/annotations.go [hunk 8]
```diff
@@ -76,6 +78,27 @@ func parseAnnotationUInt32(annotations map[string]string, annotation string) *ty
...
 }
 
+// parseUpstreamProtocols parses the annotations map for a contour.heptio.com/upstream-protocol.{protocol}
+// where 'protocol' identifies which protocol must be used in the upstream.
+// If the value is not present, or malformed, then an empty map is returned.
+func parseUpstreamProtocols(annotations map[string]string, annotation string, protocols ...string) map[string]string {
+	up := make(map[string]string)
+	for _, protocol := range protocols {
+		ports, ok := annotations[fmt.Sprintf("%s.%s", annotation, protocol)]
+		if !ok {
```
Comment (davecheney) [inline internal/contour/annotations.go]: nit: you don't need to check ok here, the zero value of ports will be "", and splitting "" on "," will result in a slice of zero entries.

Comment (glerchundi) [reply internal/contour/annotations.go]: good catch.

File: internal/contour/cluster.go (hunk 5 above)
Comment (glerchundi) [reply internal/contour/cluster.go]: Done.

File: internal/contour/annotations.go (hunk 8 above)
Comment (glerchundi) [reply internal/contour/annotations.go]: Done.

**Comment by glerchundi** [comment]
Great, thanks!
