### PR TITLE
fix envoy config to avoid overflows

### LINKED ISSUE #291: max requests overflow in envoy
I have problems with contour in production environment.
I have big cluster with huge number of endpoints (but I'm not sure that this is a reason of my problem) and when I launch envoy+contour for my cluster I get `max requests overflow` in logs:

```
[2018-03-19 16:17:16.589][33128][debug][router] source/common/router/router.cc:250] [C0][S8508896512659884808] cluster ‘contour’ match for URL ‘/envoy.api.v2.EndpointDiscoveryService/StreamEndpoints’
[2018-03-19 16:17:16.589][33128][debug][router] source/common/router/router.cc:298] [C0][S8508896512659884808]   ‘:method’:‘POST’
[2018-03-19 16:17:16.589][33128][debug][router] source/common/router/router.cc:298] [C0][S8508896512659884808]   ‘:path’:‘/envoy.api.v2.EndpointDiscoveryService/StreamEndpoints’
[2018-03-19 16:17:16.589][33128][debug][router] source/common/router/router.cc:298] [C0][S8508896512659884808]   ‘:authority’:‘contour’
[2018-03-19 16:17:16.589][33128][debug][router] source/common/router/router.cc:298] [C0][S8508896512659884808]   ‘content-type’:‘application/grpc’
[2018-03-19 16:17:16.589][33128][debug][router] source/common/router/router.cc:298] [C0][S8508896512659884808]   ‘te’:‘trailers’
[2018-03-19 16:17:16.589][33128][debug][router] source/common/router/router.cc:298] [C0][S8508896512659884808]   ‘x-envoy-internal’:‘true’
[2018-03-19 16:17:16.589][33128][debug][router] source/common/router/router.cc:298] [C0][S8508896512659884808]   ‘x-forwarded-for’:‘10.9.5.13’
[2018-03-19 16:17:16.589][33128][debug][router] source/common/router/router.cc:298] [C0][S8508896512659884808]   ‘:scheme’:‘http’
[2018-03-19 16:17:16.589][33128][debug][pool] source/common/http/http2/conn_pool.cc:93] max requests overflow
[2018-03-19 16:17:16.589][33128][debug][router] source/common/router/router.cc:464] [C0][S8508896512659884808] upstream reset
[2018-03-19 16:17:16.589][33128][debug][http] source/common/http/async_client_impl.cc:89] async http request response headers (end_stream=false):
[2018-03-19 16:17:16.589][33128][debug][http] source/common/http/async_client_impl.cc:92]   ‘:status’:‘503’
[2018-03-19 16:17:16.589][33128][debug][http] source/common/http/async_client_impl.cc:92]   ‘content-length’:‘57’
[2018-03-19 16:17:16.589][33128][debug][http] source/common/http/async_client_impl.cc:92]   ‘content-type’:‘text/plain’
[2018-03-19 16:17:16.589][33128][debug][http] source/common/http/async_client_impl.cc:92]   ‘x-envoy-overloaded’:‘true’
[2018-03-19 16:17:16.589][33128][warning][upstream] source/common/config/grpc_mux_impl.cc:205] gRPC config stream closed: 1,
[2018-03-19 16:17:16.589][33128][warning][config] bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_mux_subscription_lib/common/config/grpc_mux_subscription_impl.h:66] gRPC update for type.googleapis.com/envoy.api.v2.ClusterLoadAssignment failed
[2018-03-19 16:17:16.589][33128][warning][upstream] source/common/config/grpc_mux_impl.cc:36] Unable to establish new stream
[2018-03-19 16:17:16.589][33128][warning][config] bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_mux_subscription_lib/common/config/grpc_mux_subscription_impl.h:66] gRPC update for type.googleapis.com/envoy.api.v2.ClusterLoadAssignment failed
[2018-03-19 16:17:16.589][33128][debug][upstream] source/common/config/grpc_mux_impl.cc:33] Establishing new gRPC bidi stream for rpc StreamEndpoints(stream .envoy.api.v2.DiscoveryRequest) returns (stream .envoy.api.v2.DiscoveryResponse);

[2018-03-19 16:17:16.589][33128][debug][router] source/common/router/router.cc:250] [C0][S10460724956371150316] cluster ‘contour’ match for URL ‘/envoy.api.v2.EndpointDiscoveryService/StreamEndpoints’
[2018-03-19 16:17:16.589][33128][debug][router] source/common/router/router.cc:298] [C0][S10460724956371150316]   ‘:method’:‘POST’
[2018-03-19 16:17:16.589][33128][debug][router] source/common/router/router.cc:298] [C0][S10460724956371150316]   ‘:path’:‘/envoy.api.v2.EndpointDiscoveryService/StreamEndpoints’
[2018-03-19 16:17:16.589][33128][debug][router] source/common/router/router.cc:298] [C0][S10460724956371150316]   ‘:authority’:‘contour’
[2018-03-19 16:17:16.589][33128][debug][router] source/common/router/router.cc:298] [C0][S10460724956371150316]   ‘content-type’:‘application/grpc’
[2018-03-19 16:17:16.589][33128][debug][router] source/common/router/router.cc:298] [C0][S10460724956371150316]   ‘te’:‘trailers’
[2018-03-19 16:17:16.589][33128][debug][router] source/common/router/router.cc:298] [C0][S10460724956371150316]   ‘x-envoy-internal’:‘true’
[2018-03-19 16:17:16.589][33128][debug][router] source/common/router/router.cc:298] [C0][S10460724956371150316]   ‘x-forwarded-for’:‘10.9.5.13’
[2018-03-19 16:17:16.589][33128][debug][router] source/common/router/router.cc:298] [C0][S10460724956371150316]   ‘:scheme’:‘http’
[2018-03-19 16:17:16.589][33128][debug][pool] source/common/http/http2/conn_pool.cc:93] max requests overflow
[2018-03-19 16:17:16.589][33128][debug][router] source/common/router/router.cc:464] [C0][S10460724956371150316] upstream reset
[2018-03-19 16:17:16.589][33128][debug][http] source/common/http/async_client_impl.cc:89] async http request response headers (end_stream=false):
[2018-03-19 16:17:16.589][33128][debug][http] source/common/http/async_client_impl.cc:92]   ‘:status’:‘503’
[2018-03-19 16:17:16.589][33128][debug][http] source/common/http/async_client_impl.cc:92]   ‘content-length’:‘57’
[2018-03-19 16:17:16.589][33128][debug][http] source/common/http/async_client_impl.cc:92]   ‘content-type’:‘text/plain’
[2018-03-19 16:17:16.589][33128][debug][http] source/common/http/async_client_impl.cc:92]   ‘x-envoy-overloaded’:‘true’
[2018-03-19 16:17:16.589][33128][warning][upstream] source/common/config/grpc_mux_impl.cc:205] gRPC config stream closed: 1,
[2018-03-19 16:17:16.589][33128][warning][config] bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_mux_subscription_lib/common/config/grpc_mux_subscription_impl.h:66] gRPC update for type.googleapis.com/envoy.api.v2.ClusterLoadAssignment failed
```

These messages infinitely arrive to logs. And what's interesting, I have only one ingress resource with ingress class `contour` and despite these logs proxying works well.

It seems like I need to adjust some settings for envoy server but I don't understand which exactly.

I use latest version of contour (0.4) and envoy `version: e6ff690611b8a3373f6d66066b52d613873e446e/1.6.0-dev/Clean/RELEASE`

`lsof` doesn't give me any understanding because there is no other TCP connections from envoy to somewhere excepting the connection to contour. And I don't understand which limit envoy overflows.

### PR DESCRIPTION
**Pull request by Lookyan**
Fixes #291 
Not sure that we need to expose these parameters to be configurable. If you think so, let me know, I'll expose them.
It's necessary for big clusters.

### CODE REVIEW

**Comment by davecheney** [comment]
Thank you. I'm worried about setting these limits to arbitrary values but I think for 0.4.1 we can land this as is and take a p2 issue to bikeshed their correct values.

File: internal/envoy/config.go [hunk 1]
```diff
@@ -76,6 +76,18 @@ static_resources:
         port_value: {{ if .XDSGRPCPort }}{{ .XDSGRPCPort }}{{ else }}8001{{ end }}
     lb_policy: ROUND_ROBIN
     http2_protocol_options: {}
+    circuit_breakers:
+      thresholds:
+        - priority: high
+          max_connections: 100000
+          max_pending_requests: 100000
+          max_requests: 60000000
+          max_retries: 50
```
Comment (davecheney) [inline internal/envoy/config.go]: I'm not sure about this value. What I see in testing is 
```
contour::127.0.0.1:8001::cx_active::1
contour::127.0.0.1:8001::cx_connect_fail::2
contour::127.0.0.1:8001::cx_total::3
contour::127.0.0.1:8001::rq_active::514
contour::127.0.0.1:8001::rq_error::4
contour::127.0.0.1:8001::rq_success::0
contour::127.0.0.1:8001::rq_timeout::0
contour::127.0.0.1:8001::rq_total::518
contour::127.0.0.1:8001::health_flags::healthy
contour::127.0.0.1:8001::weight::1
contour::127.0.0.1:8001::region::
contour::127.0.0.1:8001::zone::
contour::127.0.0.1:8001::sub_zone::
contour::127.0.0.1:8001::canary::false
contour::127.0.0.1:8001::success_rate::-1
```
518 in progress connections, but nothing has timed out yet. Retrying is fine, even retrying indefinitely is fine, but I think a reasonably short _connection_ timeout, say < 5 seconds, should be applied to each attempt.

It doesn't matter so much for this change as we're going to embiggen the max incoming connections on the server side in #308, but we should revisit it in #313

**Comment by davecheney** [comment]
Thank you very much for working on this. I've tested this plys #308 and confirmed its raised the limits as we expected. 

I've squashed this because I need to backport it to the 0.4 branch.
